### PR TITLE
Goreleaser configuration 

### PR DESCRIPTION
**Pull request by AdeboyeDN**
Here are things i will need you to do

1. Add PUBLISHER_TOKEN to github secret manager 
2. Create 2 new repositories called homebrew-brew and scoop-goignore this are for brew and scoop installation

### CODE REVIEW

**Comment by hacktivist123** [comment]
Does the name of the repo for home brew have to be homebrew-brew? 

Why not homebrew-go ignore

**Comment by AdeboyeDN** [comment]
sure we can make it homebrew-goignore

**Comment by hacktivist123** [comment]
Okay, let me create the repos and setup go releaser

**Review by hacktivist123 — APPROVED** [review]
LGTM

**Pull request merged**
