### PR TITLE
added fix for language detection

### PR DESCRIPTION
**Pull request by chuksgpfr**
This PR adds a fix for the language detection feature.

### CODE REVIEW

**Comment by chuksgpfr** [comment]
@hacktivist123 I have tested. You can go ahead and test. If you have any features to add. Any I can help with

**Comment by hacktivist123** [comment]
@quamejnr check this out and let me know what you think since this relates to your PR

**Comment by quamejnr** [comment]
Yeah it looks good, wanted to first implement something like that but changed my mind later.
But in the usecase that's being proposed. considering both .js files and .ts files all have the same gitignore file, I don't quite see what change that will introduce, unless there will be an introduction of a typescript exclusive gitignore file

**Comment by hacktivist123** [comment]
Yes, there will actually be a typescript specific file soon. 

So I’m going to merge this, then you can rebase your current PR and see if you can refactor your tests a bit. Is that fine with you? @quamejnr

**Comment by quamejnr** [comment]
Yes that's fine, if the merge goes well, I think the tests will work fine or is there something else you think would change?

**Comment by hacktivist123** [comment]
Not sure, but let's see how it goes

**Pull request merged**
